### ISSUE TITLE
Remove old_round functionality

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/anydex-core#31]
In Tribler/py-ipv8#651 it was discussed and deemed safe to remove the `old_round` functionality since it's no longer necessary. However the functionality is still used here. Opening this as a parallel issue for discussion.

It is used in the following places:
https://github.com/Tribler/anydex-core/blob/asyncio/anydex/core/orderbook.py#L51
https://github.com/Tribler/anydex-core/blob/asyncio/anydex/core/orderbook.py#L70
https://github.com/Tribler/anydex-core/blob/asyncio/anydex/core/tick.py#L164
https://github.com/Tribler/anydex-core/blob/asyncio/anydex/test/core/test_order.py#L45
https://github.com/Tribler/anydex-core/blob/asyncio/anydex/test/core/test_timestamp.py#L27
https://github.com/Tribler/anydex-core/blob/asyncio/anydex/core/timestamp.py#L34
https://github.com/Tribler/anydex-core/blob/asyncio/anydex/core/timeout.py#L34
https://github.com/Tribler/anydex-core/blob/asyncio/anydex/test/core/test_timeout.py#L25

**Comment by Solomon1732** [comment]
Also opened a parallel issue Tribler/tribler#5024

**Comment by devos50** [comment]
@Solomon1732 please feel free to remove `old_round` from the linked locations in the code 👍 . Thanks!

**Comment by devos50** [comment]
Fixed by #32
