### ISSUE TITLE
Replace bare excepts with specified excepts

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/anydex-core#33]
There are a number of places containing bare excepts. Some of these places can be replaced with specified excepts, and some with `Exception`. Since some errors like `SystemExit` are derived from `BareException` and not `Exception` it might lead to unexpected *behavior.

| Location | Error raised (not exclusive) | Notes |
| --- | --- | --- |
| https://github.com/Tribler/anydex-core/blob/asyncio/anydex/core/community.py#L1155 | `RuntimeError` | https://github.com/Tribler/anydex-core/blob/asyncio/anydex/core/community.py#L1277 |
| https://github.com/Tribler/anydex-core/blob/asyncio/anydex/core/community.py#L1277 | `RuntimeError` | https://github.com/Tribler/anydex-core/blob/asyncio/anydex/core/community.py#L1277 |
| https://github.com/Tribler/anydex-core/blob/asyncio/anydex/test/instrumentation.py#L141 | None | https://docs.python.org/3/library/functions.html#repr |
| https://github.com/Tribler/anydex-core/blob/asyncio/anydex/test/util.py#L48 | None | https://docs.python.org/3/library/functions.html#repr |
| https://github.com/Tribler/anydex-core/blob/asyncio/anydex/wallet/btc_wallet.py#L85 | See notes | Seems low-level enough to see which exceptions are thrown. https://github.com/Tribler/anydex-core/blob/asyncio/anydex/wallet/btc_wallet.py#L67 and https://bitcoinlib.readthedocs.io/en/latest/source/bitcoinlib.wallets.html?highlight=utxos_update#bitcoinlib.wallets.HDWallet.utxos_update |

**Comment by Solomon1732** [comment]
Any comment on this?

**Comment by devos50** [comment]
Thanks for the poke! Currently a bit busy with our scientific article...

I agree with your summary and if you can make these changes, I'll review and accept them 👍 

Our Bitcoin wallet needs some love since we rely on a rather old version of `bitcoinlib`. Would you by any chance be interested in doing so?

**Comment by Solomon1732** [comment]
Sure, I'll PR this 😄 
> Our Bitcoin wallet needs some love since we rely on a rather old version of `bitcoinlib`. Would you by any chance be interested in doing so?

Not sure what you mean by this 😅

**Comment by Solomon1732** [comment]
Regarding https://github.com/Tribler/anydex-core/blob/asyncio/anydex/wallet/btc_wallet.py#L85; looking at the links in the note area it looks like this too doesn't raise any exceptions. Please correct me if I'm wrong

**Comment by Solomon1732** [comment]
> Our Bitcoin wallet needs some love since we rely on a rather old version of bitcoinlib. Would you by any chance be interested in doing so?

I don't mind helping to migrate it to a newer version 😄

**Comment by devos50** [comment]
Great! This is a bit of a more challenging issue I think but if you're up for the challenge you're more than welcome to try 👍 . Integration of a stable Bitcoin wallet in AnyDex (and Tribler) is something that we have been struggling with for quite some time.

**Comment by Solomon1732** [comment]
I think a new issue can be opened on this then, no? Instead of discussing it here. I don't mind opening one, I simply want to avoid doing so if there's no need.

**Comment by devos50** [comment]
Yes, please create a new issue for this, thanks! 👍
