### ISSUE TITLE
bitcoin wallet

### ISSUE THREAD

**Issue by vorticalbox** [Tribler/anydex-core#50]
##### Tribler version/branch+revision: 
7.3.2

##### Operating system and version: 
ubuntu 18.04

##### Steps to reproduce the behavior: 
try create a bitcoin wallet

##### Expected behavior: 
makes  a wallet

##### Actual behavior: 
```
bitcoinlib could not be located on your system. Please install it using the following command: pip install bitcoinlib --user
```
tried the command suggested command and also 
```
sudo apt-get install -y python3-bitcoinlib
```

**Comment by vorticalbox** [comment]
@devos50 did they ever get fixed? happy to close if no work it going to be done on it.

**Comment by devos50** [comment]
@vorticalbox no, this never got fixed. The market functionality eventually got removed from Tribler as well. Feel free to close this issue!
