### ISSUE TITLE
AssertionError: Received data from unregistered address

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/anydex-core#64]
The last three builds failed in the same test: "FAIL: Test a full trade with (dummy assets), where both traders are not connected to each other". This is the stack traceback:
https://gist.github.com/Solomon1732/1cbbffdd589c797ef2c82157c4839d6e

The specific port and IP address change of course between tests.
The builds in question:
https://jenkins-ci.tribler.org/job/anydex/job/test_anydex_linux/191/console
https://jenkins-ci.tribler.org/job/anydex/job/test_anydex_linux/193/console
https://jenkins-ci.tribler.org/job/anydex/job/test_anydex_linux/192/console

**Comment by devos50** [comment]
Thanks for reporting! What version of IPv8 are you using?

The IP address/port changes indeed for every test; this information is generated randomly every run. Note that we are not actually sending Internet traffic during these tests.

**Comment by Solomon1732** [comment]
I wasn't testing it locally. I merely noticed that the recent builds are failing in the repo :sweat_smile: So I guess the development version?

**Comment by devos50** [comment]
I disabled the conflicting test in #65. I noticed that the test runner was using a quite outdated script. I will ask the IPv8 developers for more info about this bug 👍

**Comment by devos50** [comment]
Fixed by https://github.com/Tribler/py-ipv8/pull/967
